### ISSUE TITLE
First input is not focused after error, in chrome

### ISSUE THREAD

**Issue by IanVS** [leonardodino/rci#10]
In the example sandbox, when using firefox or safari, if an invalid code is entered, after the error animation, the first field appears focused.

However, using chrome (Brave, actually), the first field is able to be typed into, but the border does not appear around the first box, it looks like this, even though the input is focused:

<img src="https://user-images.githubusercontent.com/4616705/148875014-d589b79f-fd7f-4735-8e28-eae07884bad9.png" width=300/>

When logging the arguments to `renderSegment`, the final set is:

```
{index: 0, state: null, position: -1, selection: Array(2)}
{index: 1, state: null, position: -1, selection: Array(2)}
{index: 2, state: null, position: -1, selection: Array(2)}
{index: 3, state: null, position: -1, selection: Array(2)}
{index: 4, state: null, position: -1, selection: Array(2)}
{index: 5, state: null, position: -1, selection: Array(2)}
```

Whereas in firefox, the final set includes a `cursor`:

```
{index: 0, state: "cursor", position: 1, selection: Array(2)}
{index: 1, state: null, position: 1, selection: Array(2)}
{index: 2, state: null, position: 1, selection: Array(2)}
{index: 3, state: null, position: 1, selection: Array(2)}
{index: 4, state: null, position: 1, selection: Array(2)}
{index: 5, state: null, position: 1, selection: Array(2)}
```

I'm trying to figure out why this is, but wanted to open an issue in case you might know what's going on.

**Comment by IanVS** [comment]
Oh interesting, I added a console.log in `useCodeInputHandler`, and found that it is running continuously, several times per second with a `type` of `"selectionchange"`, in firefox, but not chrome.  Will edit this comment if I find anything else...

**Comment by IanVS** [comment]
I think the main issue is that chrome does not report an `input` event (nor a `selectionchange` event) when the input value is changed programatically.  I think I can work around this in a very-slightly ugly way by adding a space and selecting it after an error, like thus:

```
input.value = ' '
input.setSelectionRange(0, 0)
```

**Comment by axelmarciano** [comment]
The function returned by useCodeInputHandler prevent this component to be controlled, IDK exactly why right now but working on a PR to make it possible.

**Comment by axelmarciano** [comment]
#https://github.com/leonardodino/rci/pull/13
This PR will fix the focus issue after error.
