### ISSUE TITLE
`autoFocus={true}` seems to not be added to the input element

### ISSUE THREAD

**Issue by jasikpark** [leonardodino/rci#12]
As you can see in [![Edit rci – CodeInput (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rci-codeinput-forked-b3z2y?fontsize=14&hidenavigation=1&theme=dark)

I edited the example to set `<Example id={a11yId} expected={expected} autoFocus={true}/>`  but there is no autofocus attribute on the input on load.

**Comment by axelmarciano** [comment]
In React, `autofocus`!== `autoFocus`.
If you use the `autofocus` props you will use the html props but with `autoFocus` the `focus()` method will be called when the component mounts.
If you want to learn more: `https://github.com/facebook/react/issues/11851#issuecomment-351672131`
