### ISSUE TITLE
react/jsx-runtime.js error nextjs

### ISSUE THREAD

**Issue by mattvb91** [leonardodino/rci#14]
Getting the following error on nextjs `v12.0.8`

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
 'node_modules/react/jsx-runtime' imported from node_modules/rci/dist/esm/index.js
Did you mean to import react/jsx-runtime.js?
```

Seems to be related to nextjs setting ` "jsx": "preserve"` in tsconfig? 

```
We detected TypeScript in your project and reconfigured your tsconfig.json file for you. Strict-mode is set to false by default.

The following mandatory changes were made to your tsconfig.json:

        - jsx was set to preserve (next.js implements its own optimized jsx transform)
```

**Comment by leonardodino** [comment]
this is solved by [react 18](https://unpkg.com/browse/react@18.0.0-rc.0/package.json#L33), either:
A) use `yarn add react@rc react-dom@rc` 
**or**
B) use [`patch-package`](https://github.com/ds300/patch-package) to add `.js` to the file.
