### ISSUE TITLE
Underlying input width

### ISSUE THREAD

**Issue by hwhmeikle** [leonardodino/rci#16]
Hey, first off thank you so much for the library - I appreciate how much effort has gone into the a11y complexities of this design pattern.

Currently the underlying `<input>` has an inline style with `width: 200%` - and this is not overridable with the `inputStyle` class as it's defined after the spread of `inputStyle`.

I noticed that when using a password manager like 1Password, it causes the little 1Password icon to appear quite far off where the dummy input appears visually:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/19391152/164560875-901f7d1f-c8f2-4630-8e81-135c2371cd45.png">

I can override the `input` width by smacking a `!important` on my own defined class e.g. `width: 120% !important,` but before I commit to this solution do I risk breaking something that I'm not aware of? It seems okay so far, but just want to double check.

Cheers!

**Comment by jasikpark** [comment]
Yep I don't think 200% is necessarily required, but the width needs to be larger for the inputs to line up

Maybe text-indent:0 is a solution?? 

https://twitter.com/drwpow/status/1496896451041021971?s=21&t=C6vuw4E1yZo4CkV2v4BvzA

**Comment by jasikpark** [comment]
It'd be great to find a solution that makes this less obvious / unneeded though

**Comment by jasikpark** [comment]
Would it work to just set it to something like `120%` so it's less wacky?
