### ISSUE TITLE
Throws an error while typing

### ISSUE THREAD

**Issue by Igor-Iugin** [leonardodino/rci#20]
Hello. I use this package with NextJS nad after update 0.0.3 i receive this error

After rollback message left

![изображение](https://user-images.githubusercontent.com/56183592/183432840-1ba8b0e8-fd97-4e08-be18-34d820e76c7f.png)

**Comment by Igor-Iugin** [comment]
I have identified the source of the error.
Error appears after adding prop `type='number'`

**Comment by leonardodino** [comment]
Hey @Igor-Iugin,

`type='number'` should not be used for this kinds of input.
please see [this article](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/#:~:text=Why%20type%3Dnumber%20is%20problematic), on the reasoning and solution.

the pattern is also implemented by default in the [example](https://github.com/leonardodino/rci/blob/9a455be180bd21df801fbdd1b4b72af0e08f2b21/apps/rci-sandbox/src/Example.tsx#L46-L48).


if problem is solved by removing it and/or replacing with the example, please close the issue 😄
