### ISSUE TITLE
Controlled input props isn't supported / doesn't work as expected

### ISSUE THREAD

**Issue by thure** [leonardodino/rci#25]
CodeSandbox reproduction here: https://codesandbox.io/s/rci-codeinput-forked-e4qg3z

### Expected
Supplying a `value: state` prop and an `onChange: setState` prop to `CodeInput` should yield similar results to [regular controlled inputs in React](https://reactjs.org/docs/forms.html#controlled-components).

### Instead
Currently the input’s `onChange` doesn't fire if `value` is also supplied, and there is a flash of the next input value before it gets reset to its initial state.

### Suggestion
Maybe an acceptable patch while investigating the issue would be to omit `value` from accepted props and not pass it to the underlying `input`.

I notice in the example the input’s value iscontrolled using the `onChange` event’s `currentTarget` instead of the usual React way — maybe `RCI.Input` needs to wrap `value` and `onChange` props in something that works with `inputRef`.

**Comment by leonardodino** [comment]
Hey there, sorry for the monumental delay 😅 

Indeed, it looks like a bug, but it's actually the only sane/reasonable way to deal with selections without reimplementing half of the OS text stack. Only the user should be able to manipulate the values for this input.

The suggestion to remove from types is 💯 that indeed is a bug to be there 🙌 

if a hacky workaround is needed, as long as it's not concurrent with user changes:
pass both a `defaultValue` and a `key` (makes sense to keep both the same)
