### ISSUE TITLE
Avoiding non-numeric input

### ISSUE THREAD

**Issue by IanVS** [leonardodino/rci#8]
Hi there!

I see in your codesandbox (also, thanks for that, it's been very helpful!) that you're using an onChange to detect non 0-9 characters and remove them.  This results in a bit of a flicker sometimes, as the value is cleared out.  

Is there a reason that an `onKeyDown` couldn't be used instead, to avoid those characters from even being set in the first place?

I suppose that the onChange would still be necessary to handle pastes...

**Comment by IanVS** [comment]
This is what I came up with, FWIW.  Do you see any glaring problems with it?

```js
const ALLOWED_KEYS = [
  'ArrowLeft',
  'ArrowRight',
  'Backspace',
  'Delete',
  'End',
  'Enter',
  'Escape',
  'Home',
  'Meta',
  'PageDown',
  'PageUp',
];


<CodeInput
    onChange={( currentTarget: input }) => {
        // remove any non-digits (e.g. from a paste)
        input.value = input.value.replace(/\D+/g, '');
      }}
    onKeyDown={(e) => {
        // Allow particular "special" keys
        if (ALLOWED_KEYS.includes(e.key)) return;

	    // Allow paste, select all
        if ((e.metaKey  || e.ctrlKey) && (e.key === 'v' | e.key === 'a') return

        // Otherwise, if a non-digit key is pressed, do nothing
        if (!/^[0-9]$/i.test(e.key)) {
          e.preventDefault();
          return;
        }
      }}

**Comment by leonardodino** [comment]
would be a valid library on its own! 😄

but: I would rather avoid the trap of allowlisting the keyboard shortcuts.
**example1**: on mac the code above breaks `^e` (Control+E), which would go to the end of the input, and most other [emac-isms](https://jblevins.org/log/kbd).
**example2**: people might run/choose systems on which paste is not `⌘v` or `ctrl+v` 😅

the premise of seamless integrating across OS/accessibility goes against allowlisting this sort of thing (:

If there's some other way to implement it, that is, only allowing input of certain characters without breaking anything else, I would gladly accept it. even though the base lib should support any type of input, the numeric case is indeed a major use-case.

**Comment by IanVS** [comment]
Those are good points, and I think you're probably right that there are edge cases I haven't considered.  For what it's worth, `^e` does work correctly, for some reason I don't quite understand.  I think perhaps a slightly improved version would be to only prevent the key if none of meta, control, or alt are also pressed.  But, like you say, there's no way to know what folks might have set up, so this probably isn't safe.  Thanks!

**Comment by jasikpark** [comment]
What if was a blanket "if special key is pressed, allow alphabetical keys to be pressed" & then if there's slipthrough they'd be caught by the input.value filter? Since it's easier to know whether a special key is pressed rather than *all* keyboard shortcuts that this might interfere with
