### ISSUE TITLE
Cannot run `yarn install`

### ISSUE THREAD

**Issue by IanVS** [leonardodino/rci#9]
I cloned the repo, and ran `yarn` to install dependencies, but I get this error message:

```
▶ yarn
rci/.yarn/releases/yarn-berry.cjs:1
version https://git-lfs.github.com/spec/v1
        ^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

The file, which claims to be a .cjs file, is actually just:

```
version https://git-lfs.github.com/spec/v1
oid sha256:57ec2d26a54c312a1848599265be6aba0e2e5f734eaba3fcd4c491429fefa21f
size 1980728
```

**Comment by IanVS** [comment]
I've tried using corepack, without any luck either.  https://github.com/nodejs/corepack/issues/79

**Comment by IanVS** [comment]
OK, I finally figured out you're using git lfs, which I've never worked with before.  Since your config here is a bit "non-standard", it might be a good idea to have a `CONTRIBUTING.md` file, 🙏 .

**Comment by leonardodino** [comment]
hadn't heard of corepack until right now! 😅

Indeed, I'm not currently happy with the currently tooling. I've just chose whatever first popped up regarding building/publishing multiple packages, that depend on each other, and a basic monorepo structure, ended up with: https://yarn.build/ didn't wasted much time as I don't have that much to devote to OSS projects at the moment 😅 

right now there are probably a dozen simpler ways to manage this project, whenever I get some time I will evaluate again, git-lfs, yarn v2, and plugins shouldn't be needed for such a tiny project, but such is the state of js tooling nowadays (:

**Comment by jasikpark** [comment]
I feel like git-lfs is the main interesting choice - since I've mainly seen that only for storing massive amounts of images with a blog in git or something similar..
